<?php
return apply_filters( 'wcss_basic_settings', array(
    'wcss_trigger_button_location'        => array(
        'title'    => __( 'Button Location', 'woo-cart-share' ),
        'desc_tip' => __( 'Change save cart button location on cart page.', 'woo-cart-share' ),
        'id'       => 'wcss_trigger_button_location',
        'type'     => 'select',
        'options'  => array(
            'off'                 => __( 'Off', 'woo-cart-share' ),
            'with_apply_coupon'   => __( 'With - Apply coupon', 'woo-cart-share' ),
            'before_checkout_btn' => __( 'Before - Proceed to checkout', 'woo-cart-share' ),
            'after_checkout_btn'  => __( 'After - Proceed to checkout', 'woo-cart-share' ),
        ),
    ),
    'wcss_rtl_status'                     => array(
        'title'    => __( 'RTL (Right to Left)', 'woo-cart-share' ),
        'desc'     => __( 'Enable/ Disable', 'woo-cart-share' ),
        'desc_tip' => __( 'If your website supports arabic or hebrew then you can enable this option.', 'woo-cart-share' ),
        'id'       => 'wcss_rtl_status',
        'type'     => 'checkbox',
    ),
    'wcss_user_can_save_cart'             => array(
        'title' => __( 'User Can Save Cart?', 'woo-cart-share' ),
        'desc'  => __( 'Enable this option if you want users can save cart.', 'woo-cart-share' ),
        'id'    => 'wcss_user_can_save_cart',
        'type'  => 'checkbox',
    ),
    'wcss_user_can_print_cart'            => array(
        'title' => __( 'User Can Print Cart?', 'woo-cart-share' ),
        'desc'  => __( 'Enable this option if you want users can print cart', 'woo-cart-share' ),
        'id'    => 'wcss_user_can_print_cart',
        'type'  => 'checkbox',
    ),
    'wcss_share_media'                    => array(
        'title'    => __( 'Select Social Media', 'woo-cart-share' ),
        'desc_tip' => __( 'You can enable or disable share media channels.', 'woo-cart-share' ),
        'id'       => 'wcss_share_media',
        'type'     => 'checkboxgroup',
        'options'  => array(
            'whatsapp'  => __( 'Whatsapp', 'woo-cart-share' ),
            'email'     => __( 'Email', 'woo-cart-share' ),
            'copy_link' => __( 'Copy Link', 'woo-cart-share' ),
            'facebook'  => __( 'Facebook', 'woo-cart-share' ),
            'twitter'   => __( 'Twitter', 'woo-cart-share' ),
            'skype'     => __( 'Skype', 'woo-cart-share' ),
            'messenger' => __( 'Messenger', 'woo-cart-share' ),
        ),
    ),
    'wcss_display_by_role_status'         => array(
        'title'    => __( 'Display By Roles', 'woo-cart-share' ),
        'desc'     => __( 'Enable/ Disable', 'woo-cart-share' ),
        'desc_tip' => __( 'You can enable or disable share cart by the roles.', 'woo-cart-share' ),
        'id'       => 'wcss_display_by_role_status',
        'type'     => 'checkbox',
    ),
    'wcss_display_by_role'                => array(
        'desc'   => __( 'Select roles', 'woo-cart-share' ),
        'id'     => 'wcss_display_by_role',
        'type'   => 'dropdown_roles',
        'class'  => 'regular-text wcss-select2',
        'select' => array(
            'multiple' => true,
        ),
    ),
    'wcss_retrieved_cart_redirection_page_id' => array(
        'title'    => __( 'Retrieved Cart Redirection', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Default: %s', 'woo-cart-share' ), '<code>' . get_the_title( get_option( 'woocommerce_cart_page_id' ) ) . '</code>' ),
        'desc_tip' => __( 'Select the page where user redirect after retrieve a shared cart.', 'woo-cart-share' ),
        'id'       => 'wcss_retrieved_cart_redirection_page_id',
        'default'  => 'none',
        'type'     => 'dropdown_pages',
        'class'    => 'regular-text wcss-select2',
    ),
    'wcss_social_share_message'           => array(
        'title'    => __( 'Social Share Message', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Use %s for the share cart link.', 'woo-cart-share' ), '<code>{link}</code>' ),
        'desc_tip' => __( 'This message will send with shared link.', 'woo-cart-share' ),
        'id'       => 'wcss_social_share_message',
        'type'     => 'textarea',
        'class'    => 'regular-text',
        'css'      => 'height:100px;',
    ),
    'wcss_custom_css'                     => array(
        'title' => __( 'Custom CSS', 'woo-cart-share' ),
        'desc'  => __( 'Enter your custom CSS.', 'woo-cart-share' ),
        'id'    => 'wcss_custom_css',
        'type'  => 'textarea',
        'class' => 'regular-text',
        'css'   => 'height:200px;background:#263238;color:#fff;font-size:13px;width:520px;max-width:100%;',
    ),
    'wscc_developemnt_settings_link'      => array(
        'title' => __( 'Developer Settings', 'woo-cart-share' ),
        'desc'  => __( 'Please do not make changes here without our permission.', 'woo-cart-share' ),
        'id'    => 'wscc_developemnt_settings_link',
        'value' => __( 'Goto developer settings', 'woo-cart-share' ),
        'link'  => admin_url( 'admin.php?page=woocommerce-cart-share_developer-settings' ),
        'type'  => 'link',
    ),

) );
