<?php
return apply_filters( 'wcss_appearance_settings', array(
    'wcss_popup_background_color'          => array(
        'title'    => __( 'Popup Background Color', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Default %s', 'woo-cart-share' ), '<code>#ffffff</code>' ),
        'desc_tip' => __( 'Change popup background color.', 'woo-cart-share' ),
        'default'  => '#ffffff',
        'id'       => 'wcss_popup_background_color',
        'type'     => 'color',
    ),
    'wcss_popup_text_color'                => array(
        'title'    => __( 'Popup Text Color', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Default %s', 'woo-cart-share' ), '<code>#21234a</code>' ),
        'desc_tip' => __( 'Change popup text color.', 'woo-cart-share' ),
        'default'  => '#21234a',
        'id'       => 'wcss_popup_text_color',
        'type'     => 'color',
    ),
    'wcss_button_background_color'         => array(
        'title'    => __( 'Buttons Background Color', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Default %s', 'woo-cart-share' ), '<code>#fc6c6c</code>' ),
        'desc_tip' => __( 'Change buttons background color.', 'woo-cart-share' ),
        'default'  => '#fc6c6c',
        'id'       => 'wcss_button_background_color',
        'type'     => 'color',
    ),
    'wcss_button_text_color'               => array(
        'title'    => __( 'Buttons Text Color', 'woo-cart-share' ),
        'desc'     => sprintf( __( 'Default %s', 'woo-cart-share' ), '<code>#ffffff</code>' ),
        'desc_tip' => __( 'Change buttons text color.', 'woo-cart-share' ),
        'default'  => '#ffffff',
        'id'       => 'wcss_button_text_color',
        'type'     => 'color',
    ),
    'wcss_popup_overlay_status'            => array(
        'title'   => __( 'Popup Overlay', 'woo-cart-share' ),
        'desc'    => __( 'Enable/ Disable', 'woo-cart-share' ),
        'default' => 'yes',
        'id'      => 'wcss_popup_overlay_status',
        'type'    => 'checkbox',
    ),
    'wcss_share_cart_button_text'          => array(
        'title' => __( 'Share Cart Button Text', 'woo-cart-share' ),
        'desc'  => __( 'Change share cart button text.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_button_text',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_share_cart_title'                => array(
        'title' => __( 'Share Cart Title', 'woo-cart-share' ),
        'desc'  => __( 'Change share cart title message.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_title',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_save_cart_button_text'           => array(
        'title' => __( 'Save Cart Button Text', 'woo-cart-share' ),
        'desc'  => __( 'Change save cart button text.', 'woo-cart-share' ),
        'id'    => 'wcss_save_cart_button_text',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_login_now_button_text'           => array(
        'title' => __( 'Login Now Button Text', 'woo-cart-share' ),
        'desc'  => __( 'Enter the login now button text for non logged in users.', 'woo-cart-share' ),
        'id'    => 'wcss_login_now_button_text',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_save_cart_input_placeholder'     => array(
        'title' => __( 'Save Cart Input Placeholder', 'woo-cart-share' ),
        'desc'  => __( 'Change save cart input box placeholder.', 'woo-cart-share' ),
        'id'    => 'wcss_save_cart_input_placeholder',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_save_cart_message'               => array(
        'title' => __( 'Save Cart Message', 'woo-cart-share' ),
        'desc'  => __( 'Change save cart message.', 'woo-cart-share' ),
        'id'    => 'wcss_save_cart_message',
        'type'  => 'textarea',
        'class' => 'regular-text',
        'css'   => 'height:100px;',
    ),
    'wcss_save_cart_not_logged_in_message' => array(
        'title' => __( 'Save Cart Not Logged in Message', 'woo-cart-share' ),
        'desc'  => __( 'Change save cart message if user not logged in.', 'woo-cart-share' ),
        'id'    => 'wcss_save_cart_not_logged_in_message',
        'type'  => 'textarea',
        'class' => 'regular-text',
        'css'   => 'height:100px;',
    ),
    'wcss_empty_cart_message'              => array(
        'title' => __( 'Empty Cart Message', 'woo-cart-share' ),
        'desc'  => __( 'Enter message for empty cart message.', 'woo-cart-share' ),
        'id'    => 'wcss_empty_cart_message',
        'type'  => 'wp_editor',
    ),
    'wcss_cart_retrieved_message'          => array(
        'title' => __( 'Empty Retrieved Message', 'woo-cart-share' ),
        'desc'  => __( 'Enter message for successfully cart retrieved.', 'woo-cart-share' ),
        'id'    => 'wcss_cart_retrieved_message',
        'type'  => 'textarea',
        'class' => 'regular-text',
        'css'   => 'height:100px;',
    ),
    'wcss_cart_not_found_message'          => array(
        'title' => __( 'Cart Not Found Message', 'woo-cart-share' ),
        'desc'  => __( 'Enter message for cart not found.', 'woo-cart-share' ),
        'id'    => 'wcss_cart_not_found_message',
        'type'  => 'textarea',
        'class' => 'regular-text',
        'css'   => 'height:100px;',
    ),
    'wcss_share_cart_email_to_label'       => array(
        'title' => __( 'Label For Email To', 'woo-cart-share' ),
        'desc'  => __( 'Enter the label for email to.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_email_to_label',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_share_cart_email_subject_label'  => array(
        'title' => __( 'Label For Subject', 'woo-cart-share' ),
        'desc'  => __( 'Enter the label for email subject.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_email_subject_label',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_share_cart_email_message_label'  => array(
        'title' => __( 'Label For Message', 'woo-cart-share' ),
        'desc'  => __( 'Enter the label for email message.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_email_message_label',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
    'wcss_share_cart_email_button_text'    => array(
        'title' => __( 'Send Cart Button Text', 'woo-cart-share' ),
        'desc'  => __( 'Enter the label for share cart button under the email form.', 'woo-cart-share' ),
        'id'    => 'wcss_share_cart_email_button_text',
        'type'  => 'text',
        'class' => 'regular-text',
    ),
) );
